### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by ZengEthan** [Haoliu-cola/COLA#1]
Sorry to bother you, but I want to ask that why it displayed ModuleNotFoundError: No module named 'torch.nn.functional' when I ran it. I set the environment according to the requirement, but the wrong may be caused by the version of Pytorch I saw in the Internet. Thank you!

**Comment by Haoliu-cola** [comment]
Hi, could you check your pytorch version?  I can import torch.nn.functional in my own environments with torch version 1.12 and 1.13.

**Comment by ZengEthan** [comment]
> Hi, could you check your pytorch version? I can import torch.nn.functional in my own environments with torch version 1.12 and 1.13.

Thank you for your reply! My torch version is 1.13 just as the requirement, but I can't import torch.nn.functional. 
![微信图片_20240510150555](https://github.com/Haoliu-cola/COLA/assets/125627692/6aaf6692-9c9a-421f-968d-4f1d3ec748dc)

**Comment by Haoliu-cola** [comment]
Could you provide the script you use to set up the environment so that I can reproduce the error?

**Comment by ZengEthan** [comment]
> Could you provide the script you use to set up the environment so that I can reproduce the error?

Hi, thank you for your reply! I have run correctly. It's indeed a good work and I'm looking forward to communicating with you~

**Comment by Haoliu-cola** [comment]
Thanks! Let me know if you have any other questions.

**Comment by ZengEthan** [comment]
Hi,bro! I have a question about the dataset that whether the test set and the valid set involved in the pre-training phase and/or fine-tuning phase. Or just the train set ueses in the pre-training?

**Comment by Haoliu-cola** [comment]
Hi, the whole graph is included in the pre-training phase just like what graph contrastive learning works did, and note that the label of the test set is not used.

**Comment by ZengEthan** [comment]
Hi, bro! Thank you for your reply. I want to ask another question that the 'few-shot' means the few number nodes for a class or the few labels for a class in test set? I am looking forward to your reply!

**Comment by Haoliu-cola** [comment]
Hi, few-shot means for some classes we only have limited number of labeled samples. An N-way k-shot task means we have k labeled samples for each of the N classes, and would like to classify a new sample into one of these N classes.
